# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ACV-19' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'AFNetworking', '4.0.1', :subspecs => [‘NSURLSession’]
  pod 'GoogleMaps'
  pod 'GooglePlaces'
end

